import base64
import json

import pytest

from pr_agent.policy import apply_maintainer_stance, check, classify


def test_ban_wins_over_disclosure():
    texts = {
        "CONTRIBUTING.md": "Please disclose any AI assistance in your PR.\nWe do not accept pull requests generated by AI tools.\n",
    }
    verdict, claim, matches = classify(texts, [])
    assert verdict == "bans"
    assert matches[0].startswith("ban: We do not accept pull requests generated by AI")


def test_disclosure_required():
    verdict, _, matches = classify({"CONTRIBUTING.md": "If you used an LLM, mention it in the PR description."}, [])
    assert verdict == "allows-with-disclosure"
    assert "LLM" in matches[0]


def test_explicit_welcome():
    verdict, _, _ = classify({"CONTRIBUTING.md": "AI-assisted contributions are welcome as long as you test them."}, [])
    assert verdict == "allows"


def test_agent_instruction_files_count_as_allow():
    verdict, _, matches = classify({"CONTRIBUTING.md": "Run the tests before opening a PR."}, ["AGENTS.md"])
    assert verdict == "allows"
    assert "AGENTS.md" in matches[0]


def test_no_policy_is_unclear_and_claim_detected():
    verdict, claim, matches = classify({"CONTRIBUTING.md": "Before you start working on an issue, comment on it so we can assign it to you."}, [])
    assert verdict == "unclear"
    assert claim is True
    assert matches == ["claim: Before you start working on an issue, comment on it so we can assign it to you."]


def test_a_heads_up_comment_is_not_a_claim_rule():
    # NousResearch/hermes-agent's CONTRIBUTING (2026-10-09): asks for a heads-up, never a yes.
    hermes = "Before You Start\nSearch First: check existing issues and PRs. For larger work, comment on the issue to signal you're working on it."
    assert classify({"CONTRIBUTING.md": hermes}, [])[1] is False
    kubeflow = "Wait for a member from the Kubeflow Pipelines team to respond. After you get formal approval, you can start working."
    splink = "Please wait for a maintainer to confirm that a pull request would be welcome and to agree its scope."
    assert classify({"CONTRIBUTING.md": kubeflow}, [])[1] is True
    assert classify({"CONTRIBUTING.md": splink}, [])[1] is True


def test_verdicts_cached_under_older_rules_are_redone(tmp_path):
    from pr_agent.policy import RULES, check
    from pr_agent.state import write_json
    write_json(tmp_path / "o__r.json", {"repo": "o/r", "verdict": "unclear", "claim_required": True, "files": [], "checked_at": "2099-01-01T00:00:00+00:00"})

    class GH:
        def file_text(self, repo, path):
            return None

        def list_dir(self, repo, path):
            return []

    v = check(GH(), "o/r", tmp_path)
    assert v.claim_required is False and v.rules == RULES


def test_unrelated_not_words_do_not_ban():
    verdict, _, _ = classify({"CONTRIBUTING.md": "Do not open a PR without tests. Our agents module handles retries."}, [])
    assert verdict == "unclear"


def b64(text):
    return {"encoding": "base64", "content": base64.b64encode(text.encode()).decode()}


def test_check_reads_files_and_caches(gh, fake, tmp_path):
    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("AI generated pull requests will be closed."))
    v = check(gh, "o/r", tmp_path)
    assert v.verdict == "bans" and not v.continues
    n_calls = len(fake.calls)
    again = check(gh, "o/r", tmp_path)
    assert again.verdict == "bans"
    assert len(fake.calls) == n_calls


def test_maintainer_discussion_turns_unclear_into_ban(gh, fake, tmp_path):
    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("Thanks for contributing!"))
    v = check(gh, "o/r", tmp_path)
    assert v.verdict == "unclear"
    hits = [{"url": "https://github.com/o/r/pull/5", "passages": [{"text": "Closing: we don't accept LLM generated PRs here."}]}]
    v = apply_maintainer_stance(v, hits, tmp_path)
    assert v.verdict == "bans"
    assert v.maintainer_evidence == "https://github.com/o/r/pull/5"
    assert check(gh, "o/r", tmp_path).verdict == "bans"


def test_block_is_permanent(gh, fake, tmp_path):
    from pr_agent.policy import block

    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("AI-assisted contributions are welcome."))
    assert check(gh, "o/r", tmp_path).verdict == "allows"
    block(tmp_path, "o/r", "please don't send AI PRs", "https://github.com/o/r/issues/3#c1")
    v = check(gh, "o/r", tmp_path, refresh=True)
    assert v.verdict == "bans" and not v.permits(allow_unclear=True)
    assert v.maintainer_evidence.endswith("#c1")


def test_unclear_only_continues_when_switched_on(gh, fake, tmp_path):
    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("Thanks for contributing!"))
    v = check(gh, "o/r", tmp_path)
    assert not v.permits() and v.permits(allow_unclear=True)


@pytest.mark.parametrize("text", [
    "No AI-generated code.",
    "We don't want AI-generated pull requests.",
    "Please refrain from submitting LLM-generated PRs.",
    "- No AI contributions, please.",
])
def test_plain_bans_are_bans(text):
    assert classify({"CONTRIBUTING.md": text}, [])[0] == "bans"


def test_block_list_ignores_case(tmp_path):
    from pr_agent.policy import block, is_blocked
    block(tmp_path, "Org/Repo", "no AI please", "https://github.com/Org/Repo/issues/1#c")
    assert is_blocked(tmp_path, "org/repo")
    block(tmp_path, "org/repo", "again", "x")
    assert len(json.loads((tmp_path / "blocked.json").read_text())) == 1
