import base64

from pr_agent.policy import apply_maintainer_stance, check, classify


def test_ban_wins_over_disclosure():
    texts = {
        "CONTRIBUTING.md": "Please disclose any AI assistance in your PR.\nWe do not accept pull requests generated by AI tools.\n",
    }
    verdict, claim, matches = classify(texts, [])
    assert verdict == "bans"
    assert matches[0].startswith("ban: We do not accept pull requests generated by AI")


def test_disclosure_required():
    verdict, _, matches = classify({"CONTRIBUTING.md": "If you used an LLM, mention it in the PR description."}, [])
    assert verdict == "allows-with-disclosure"
    assert "LLM" in matches[0]


def test_explicit_welcome():
    verdict, _, _ = classify({"CONTRIBUTING.md": "AI-assisted contributions are welcome as long as you test them."}, [])
    assert verdict == "allows"


def test_agent_instruction_files_count_as_allow():
    verdict, _, matches = classify({"CONTRIBUTING.md": "Run the tests before opening a PR."}, ["AGENTS.md"])
    assert verdict == "allows"
    assert "AGENTS.md" in matches[0]


def test_no_policy_is_unclear_and_claim_detected():
    verdict, claim, matches = classify({"CONTRIBUTING.md": "Before you start working on an issue, comment on it so we can assign it to you."}, [])
    assert verdict == "unclear"
    assert claim is True
    assert matches == []


def test_unrelated_not_words_do_not_ban():
    verdict, _, _ = classify({"CONTRIBUTING.md": "Do not open a PR without tests. Our agents module handles retries."}, [])
    assert verdict == "unclear"


def b64(text):
    return {"encoding": "base64", "content": base64.b64encode(text.encode()).decode()}


def test_check_reads_files_and_caches(gh, fake, tmp_path):
    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("AI generated pull requests will be closed."))
    v = check(gh, "o/r", tmp_path)
    assert v.verdict == "bans" and not v.continues
    n_calls = len(fake.calls)
    again = check(gh, "o/r", tmp_path)
    assert again.verdict == "bans"
    assert len(fake.calls) == n_calls


def test_maintainer_discussion_turns_unclear_into_ban(gh, fake, tmp_path):
    fake.add("GET", "/repos/o/r/contents/CONTRIBUTING.md", b64("Thanks for contributing!"))
    v = check(gh, "o/r", tmp_path)
    assert v.verdict == "unclear"
    hits = [{"url": "https://github.com/o/r/pull/5", "passages": [{"text": "Closing: we don't accept LLM generated PRs here."}]}]
    v = apply_maintainer_stance(v, hits, tmp_path)
    assert v.verdict == "bans"
    assert v.maintainer_evidence == "https://github.com/o/r/pull/5"
    assert check(gh, "o/r", tmp_path).verdict == "bans"
